"""Helpers for resolving project directories from seed and runtime context."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger(__name__)


@dataclass(frozen=True, slots=True)
class SeedProjectPathResolution:
    """Outcome of resolving a seed-encoded project directory.

    Distinguishes the two ``path is None`` cases that callers previously
    conflated:

    * ``rejected=False`` — the seed encoded no project path, or the seed
      was ``None``. Falling back to the caller's stable base is safe.
    * ``rejected=True`` — at least one path was encoded but every
      candidate escaped ``stable_base``. The seed *intended* to point
      somewhere; the caller must surface that explicitly (audit log,
      tool error, etc.) rather than silently running in the base
      directory.
    """

    path: Path | None
    rejected: bool


def resolve_path_against_base(
    raw_path: str | Path | None,
    *,
    stable_base: Path,
    enforce_containment: bool = False,
) -> Path | None:
    """Resolve a path against a stable base directory.

    When ``enforce_containment`` is True the resolved path (after tilde
    expansion and symlink resolution) must live inside ``stable_base``;
    otherwise ``None`` is returned and a containment-violation warning is
    logged. Callers handling untrusted input (e.g. seed-encoded paths) must
    opt in so absolute paths and ``..`` traversal cannot escape the
    project directory.
    """
    if raw_path is None:
        return None

    candidate = Path(raw_path).expanduser()
    if candidate.is_absolute():
        resolved = candidate.resolve()
    else:
        resolved = (stable_base / candidate).resolve()

    if enforce_containment:
        base_resolved = stable_base.resolve()
        if resolved != base_resolved:
            try:
                resolved.relative_to(base_resolved)
            except ValueError:
                log.warning(
                    "project_paths.containment_violation",
                    raw_path=str(raw_path),
                    resolved=str(resolved),
                    stable_base=str(base_resolved),
                )
                return None

    return resolved


def project_path_candidates_from_seed(seed: Any) -> tuple[str, ...]:
    """Extract likely project directories from seed metadata and brownfield refs."""
    if seed is None:
        return ()

    candidates: list[str] = []
    seed_meta = getattr(seed, "metadata", None)
    if seed_meta is not None:
        project_dir = getattr(seed_meta, "project_dir", None) or getattr(
            seed_meta,
            "working_directory",
            None,
        )
        if isinstance(project_dir, str) and project_dir:
            candidates.append(project_dir)

    brownfield_context = getattr(seed, "brownfield_context", None)
    context_references = getattr(brownfield_context, "context_references", ()) or ()

    for reference in context_references:
        path = getattr(reference, "path", None)
        role = getattr(reference, "role", None)
        if isinstance(path, str) and path and role == "primary" and path not in candidates:
            candidates.append(path)

    for reference in context_references:
        path = getattr(reference, "path", None)
        if isinstance(path, str) and path and path not in candidates:
            candidates.append(path)

    return tuple(candidates)


def resolve_seed_project_path(seed: Any, *, stable_base: Path) -> SeedProjectPathResolution:
    """Resolve the highest-priority project path encoded in a seed.

    Seed-encoded paths originate from untrusted sources — seeds may be
    imported via ``ooo publish`` or generated by an LLM — so every candidate
    is required to resolve inside ``stable_base``. Candidates are tried in
    priority order (metadata first, then primary brownfield references,
    then remaining references); each escaping candidate is rejected with a
    containment-violation log entry, and the next candidate is evaluated.

    Returns a :class:`SeedProjectPathResolution`:

    * ``path is not None``  — a contained candidate was found and is
      returned. ``rejected`` is ``False``.
    * ``path is None``, ``rejected=False`` — the seed encoded no project
      paths (empty seed or no metadata/brownfield references).
    * ``path is None``, ``rejected=True`` — at least one candidate was
      encoded but every candidate escaped ``stable_base``. Callers must
      treat this as an explicit security event, not a benign empty seed.
    """
    candidates = project_path_candidates_from_seed(seed)
    if not candidates:
        return SeedProjectPathResolution(path=None, rejected=False)

    for candidate in candidates:
        resolved = resolve_path_against_base(
            candidate,
            stable_base=stable_base,
            enforce_containment=True,
        )
        if resolved is not None:
            return SeedProjectPathResolution(path=resolved, rejected=False)

    return SeedProjectPathResolution(path=None, rejected=True)
